informatica_informatica:
    resource: "@informaticaInformaticaBundle/Resources/config/routing.yml"
    prefix:   /

mnz_infomrmatica:
    resource: "@mnzInfomrmaticaBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
